---
# tasks file for avahi_aliases

- name: Install avahi and avahi-aliases for Debian Bullseye and later.
  block:
  - name: Install avahi and other requirements.
    apt:
      name:
        - python3-avahi
        - python3-pip
        - avahi-daemon
        - git
        - libnss-mdns
        - python3-daemon
      state: present
      update_cache: yes
      cache_valid_time: "{{APT_CACHE_VALID_TIME}}"

  - name: Install avahi-aliases.
    pip:
      name: git+https://github.com/airtonix/avahi-aliases.git
      extra_args: --break-system-packages

  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11

- name: Install avahi and aliases.
  block:
  - name: Install avahi and other requirements.
    apt:
      name:
        - python-avahi
        - python-pip
        - avahi-daemon
        - git
        - libnss-mdns
        - python-daemon
      state: present
      update_cache: yes
      cache_valid_time: "{{APT_CACHE_VALID_TIME}}"

  - name: Install avahi-aliases.
    pip:
      name: git+https://github.com/airtonix/avahi-aliases.git

  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 11

- name: Create aliases directory.
  file:
    path=/etc/avahi/aliases.d
    state=directory
    owner=root
    group=root
    mode=0755

- name: Copy init.d script for avahi-alias.
  copy:
    src=avahi-alias
    dest=/etc/init.d/avahi-alias
    owner=root
    group=root
    mode=0755

- service:
    name=avahi-alias
    enabled=yes
    state=started
    pattern=avahi-alias

- name: Template domains.
  template:
    src: aliases.j2
    dest: "{{AVAHI_ALIASES_CONFIG_DIR}}/aliases"
  notify:
    - restart avahi-alias
