---
# tasks file for avahi_aliases

- name: Install avahi and other requirements.
  apt:
    pkg={{item}}
    state=present
    update_cache=yes
    cache_valid_time={{APT_CACHE_VALID_TIME}}
  with_items:
    - python-avahi
    - python-pip
    - avahi-daemon
    - git
    - libnss-mdns
    - python-daemon


# Need to run manually until https://github.com/ansible/ansible-modules-core/pull/227
- name: Install avahi-aliases
  command: /usr/bin/pip install git+https://github.com/airtonix/avahi-aliases.git



- name: Create aliases directory.
  file:
    path=/etc/avahi/aliases.d
    state=directory
    owner=root
    group=root
    mode=0755

- name: Copy init.d script for avahi-alias.
  copy:
    src=avahi-alias
    dest=/etc/init.d/avahi-alias
    owner=root
    group=root
    mode=0755

- service:
    name=avahi-alias
    enabled=yes
    state=started
    pattern=avahi-alias
